# backup job definitions

# Common base paths
docker_projects="/mnt/nvme/files/docker projects"

# Docker projects (example)
# backup "sample" "$docker_projects/sample_project"

# Non-Docker directories
backup "bash-scripts" "/root/scripts"
backup "acme" "/root/.acme.sh"
backup "cron" "/var/spool/cron/crontabs"
backup "nginx" "/etc/nginx"
backup "syncthing" "/root/.config/syncthing"
backup "samba" "/etc/samba"
backup "samba_credentials" "/root/.samba"