---
- hosts:
    - debian
  # Runs on root user already
  become: false
  tasks:
    - name: Start All Services
      command: tmux new-session -d -s "start_services" "bash /root/scripts/start_services.sh"
