---
- hosts:
    - debian
  # Runs on root user already
  become: false
  tasks:
    - name: Update Docker
      apt:
        name: docker
        update_cache: true
        autoremove: true
        state: latest
    - name: Update all packages
      apt:
        name: "*"
        update_cache: false
        autoremove: true
        state: latest
    - name: Update ACME
      command: /root/.acme.sh/acme.sh --upgrade --auto-upgrade
    - name: Restart All Services
      command: bash "/root/scripts/start_services.sh"
